select
  'v4_wave1_exact_function_rewrite_plan_production_gate' as section,
  88 as wave1_count,
  88 as public_compatibility_views,
  88 as owner_schema_tables,
  77 as exact_function_candidates_exported,
  45 as candidates_with_public_qualified_references,
  32 as candidates_exported_owner_review,
  false as exact_body_rewrite_applied_by_this_script,
  false as owner_approval_recorded_by_this_script,
  false as role_rls_uat_confirmed_by_this_script,
  false as browser_uat_confirmed_by_this_script,
  false as compatibility_views_removal_authorized,
  false as grant_revoke_authorized,
  false as wave3_move_authorized,
  false as production_approved,
  'PRODUCTION_BLOCKED_PENDING_PER_LANE_OWNER_APPROVAL_AND_REWRITE_APPLY_GATE' as decision,
  true as read_only;
