select
  'auth_token_400_classification'::text as section,
  'admin_console_warning'::text as warning_key,
  'POST /auth/v1/token?grant_type=password 400 (Bad Request)'::text as observed_warning,
  'AUTH_SESSION_WARNING_NOT_SERVICE_CENTER_DB_FAILURE'::text as current_classification,
  'Clean admin console retest or explicit Auth/session diagnostic required before strict production approval.'::text as required_next_evidence,
  false as execution_authorized_by_this_script,
  false as production_approved,
  false as destructive_sql_authorized,
  false as exact_public_table_replacement_authorized,
  false as archive_delete_authorized,
  true as no_auth_users_migration,
  true as no_flutter_elevated_secret,
  true as no_waqf_assets_mutation,
  true as no_gis_mutation,
  true as read_only;
