select
  'public_legacy_final_dependency_closure'::text as section,
  'PUBLIC_LEGACY_FINAL_DEPENDENCY_CLOSURE_ACCEPTED_NO_DELETE_NO_REWRITE'::text as decision,
  true as flutter_static_scan_accepted,
  true as sql_view_definition_followup_accepted,
  true as preserve_public_legacy_tables,
  true as service_navigation_owner_separation_deferred,
  false as deletion_authorized_by_this_script,
  false as rewrite_authorized_by_this_script,
  false as destructive_sql_authorized,
  false as exact_public_table_replacement_authorized,
  false as archive_delete_authorized,
  false as production_approved,
  true as no_auth_users_migration,
  true as no_flutter_elevated_secret,
  true as no_waqf_assets_mutation,
  true as no_gis_mutation,
  true as read_only;
