with wave1(public_table, target_schema, target_table, sensitivity, proposed_wave_after_retest, gate_status_after_retest) as (
  values
    ('awqaf_assist_answer_contracts', 'awqaf_system', 'awqaf_assist_answer_contracts', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_assist_workspace_items', 'awqaf_system', 'awqaf_assist_workspace_items', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_system_content', 'awqaf_system', 'awqaf_system_content', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_system_institution_profile', 'awqaf_system', 'awqaf_system_institution_profile', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_system_settings', 'awqaf_system', 'awqaf_system_settings', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_system_unit_pages', 'awqaf_system', 'awqaf_system_unit_pages', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('documents', 'cms', 'documents', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('pwf_complaint_attachments', 'complaints', 'pwf_complaint_attachments', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('pwf_complaint_updates', 'complaints', 'pwf_complaint_updates', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('pwf_complaints', 'complaints', 'pwf_complaints', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('pwf_complaints_retention_policies', 'complaints', 'pwf_complaints_retention_policies', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_community_document_evidence_links', 'core', 'awqaf_community_document_evidence_links', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('cities', 'core', 'cities', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('governorates', 'core', 'governorates', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('historical_admin_units', 'hist', 'historical_admin_units', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('historical_layers', 'hist', 'historical_layers', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('historical_periods', 'hist', 'historical_periods', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('land_admin_history', 'hist', 'land_admin_history', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('daily_habits', 'legacy_quarantine', 'daily_habits', 'low', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('intelligentrecommendations', 'legacy_quarantine', 'intelligentrecommendations', 'low', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('activities', 'media_center', 'activities', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('announcement_items', 'media_center', 'announcement_items', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('announcements', 'media_center', 'announcements', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('categories', 'media_center', 'categories', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('media_center_audit_events', 'media_center', 'media_center_audit_events', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('media_center_editorial_events', 'media_center', 'media_center_editorial_events', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('media_center_editorial_roles', 'media_center', 'media_center_editorial_roles', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('media_center_permission_uat_events', 'media_center', 'media_center_permission_uat_events', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('media_center_publishing_governance_rules', 'media_center', 'media_center_publishing_governance_rules', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('media_gallery_items', 'media_center', 'media_gallery_items', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('news', 'media_center', 'news', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('news_articles', 'media_center', 'news_articles', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('news_items', 'media_center', 'news_items', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('social_notices', 'media_center', 'social_notices', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('achievements', 'ministry_profile', 'achievements', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('former_ministers', 'ministry_profile', 'former_ministers', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('pwf_former_ministers', 'ministry_profile', 'pwf_former_ministers', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('mustakshif_announcements', 'mustakshif_staging', 'mustakshif_announcements', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('mustakshif_news', 'mustakshif_staging', 'mustakshif_news', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('mustakshif_site_pages', 'mustakshif_staging', 'mustakshif_site_pages', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('admin_users', 'platform_access', 'admin_users', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('platform_permissions', 'platform_access', 'platform_permissions', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('platform_systems', 'platform_access', 'platform_systems', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('user_accounts', 'platform_access', 'user_accounts', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('user_permissions', 'platform_access', 'user_permissions', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('user_scope_assignment_units', 'platform_access', 'user_scope_assignment_units', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('user_scope_assignments', 'platform_access', 'user_scope_assignments', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('user_system_permissions', 'platform_access', 'user_system_permissions', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('user_system_roles', 'platform_access', 'user_system_roles', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('site_pages', 'platform_content', 'site_pages', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('app_settings', 'platform_experience', 'app_settings', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('breaking_news', 'platform_experience', 'breaking_news', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('footer_settings', 'platform_experience', 'footer_settings', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('header_settings', 'platform_experience', 'header_settings', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('hero_slides', 'platform_experience', 'hero_slides', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('home_config', 'platform_experience', 'home_config', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('home_hero_slides', 'platform_experience', 'home_hero_slides', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('home_news', 'platform_experience', 'home_news', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('home_stats', 'platform_experience', 'home_stats', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('homepage_sections', 'platform_experience', 'homepage_sections', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('site_settings', 'platform_experience', 'site_settings', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('home_services', 'platform_navigation', 'home_services', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('services', 'platform_navigation', 'services', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('notifications', 'platform_notifications', 'notifications', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('reports', 'platform_reporting', 'reports', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('appointments', 'platform_services', 'appointments', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('servicepoints', 'platform_services', 'servicepoints', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('serviceproviders', 'platform_services', 'serviceproviders', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('servicetypes', 'platform_services', 'servicetypes', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('friday_sermons', 'religious_affairs', 'friday_sermons', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('islamic_terms', 'religious_affairs', 'islamic_terms', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('mosques', 'religious_affairs', 'mosques', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('task_statistics', 'tasks', 'task_statistics', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('task_status_history', 'tasks', 'task_status_history', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('task_statuses', 'tasks', 'task_statuses', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('task_types', 'tasks', 'task_types', 'medium', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_historical_topology_nodes', 'topology', 'awqaf_historical_topology_nodes', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_historical_topology_relations', 'topology', 'awqaf_historical_topology_relations', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('historical_child_level_policy', 'topology', 'historical_child_level_policy', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('historical_cluster_anchor_registry', 'topology', 'historical_cluster_anchor_registry', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('historical_parent_seed_matrix', 'topology', 'historical_parent_seed_matrix', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('historical_seed_decision_registry', 'topology', 'historical_seed_decision_registry', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('waqf_community_lineage', 'topology', 'waqf_community_lineage', 'medium-high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('assettypes', 'waqf', 'assettypes', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('awqaf_reference_waqf_links', 'waqf', 'awqaf_reference_waqf_links', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('endowment_supervisors', 'waqf', 'endowment_supervisors', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('waqf_lands', 'waqf', 'waqf_lands', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES'),
    ('zakat_donation_requests', 'zakat', 'zakat_donation_requests', 'high', 'WAVE_1_NON_COLLISION_MOVE_CANDIDATE_AFTER_APPROVAL', 'CANDIDATE_AFTER_OWNER_FLUTTER_BACKUP_RLS_GATES')
)
select
  'v4_wave1_target_schema_summary' as section,
  target_schema,
  count(*) as wave1_candidate_table_count,
  string_agg(distinct sensitivity, ', ' order by sensitivity) as sensitivity_levels,
  false as apply_authorized_by_this_script,
  false as production_approved,
  true as read_only
from wave1
group by target_schema
order by target_schema;
