-- Platform Development 10B
-- Owner-Write RPC Executable Implementation Pack
-- Scope: create guarded owner-write RPCs for core/admin/platform write paths.
-- This script is intentionally non-destructive. It does not migrate auth.users,
-- does not touch waqf/waqf_assets/awqaf_system, and does not authorize production.

begin;

create table if not exists platform.owner_write_rpc_runtime_flags (
  flag_key text primary key,
  is_enabled boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into platform.owner_write_rpc_runtime_flags(flag_key, is_enabled, metadata)
values
  ('owner_write_rpc_sql_installed_v1', true, jsonb_build_object('batch','platform_development_10b','installed_at', now())),
  ('flutter_owner_write_reroute_enabled_v1', false, jsonb_build_object('reason','Must be enabled explicitly by Dart define and after UAT evidence')),
  ('owner_write_rpc_production_approved_v1', false, jsonb_build_object('reason','Production gate remains closed until Role/RLS/Browser Console and Negative UAT pass'))
on conflict (flag_key) do update
set is_enabled = excluded.is_enabled,
    metadata = platform.owner_write_rpc_runtime_flags.metadata || excluded.metadata,
    updated_at = now();

create table if not exists platform.owner_write_rpc_audit_events (
  id bigint generated by default as identity primary key,
  event_key text not null,
  actor_user_id uuid,
  target_schema text not null,
  target_table text not null,
  target_user_id uuid,
  target_system_key text,
  request_payload jsonb not null default '{}'::jsonb,
  result_payload jsonb not null default '{}'::jsonb,
  correlation_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_owner_write_rpc_audit_actor_created
  on platform.owner_write_rpc_audit_events(actor_user_id, created_at desc);
create index if not exists idx_owner_write_rpc_audit_target_created
  on platform.owner_write_rpc_audit_events(target_schema, target_table, created_at desc);

create or replace function platform._pwf_table_exists_v1(p_schema text, p_table text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select exists (
    select 1
    from pg_catalog.pg_class c
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    where n.nspname = p_schema
      and c.relname = p_table
      and c.relkind in ('r','p','v','m')
  );
$$;

create or replace function platform._pwf_column_exists_v1(p_schema text, p_table text, p_column text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog
as $$
  select exists (
    select 1
    from pg_catalog.pg_attribute a
    join pg_catalog.pg_class c on c.oid = a.attrelid
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    where n.nspname = p_schema
      and c.relname = p_table
      and a.attname = p_column
      and a.attnum > 0
      and not a.attisdropped
  );
$$;

create or replace function platform._pwf_json_cast_expr_v1(p_json_param text, p_column text, p_type text)
returns text
language plpgsql
stable
security definer
set search_path = pg_catalog
as $$
begin
  if p_type in ('json','jsonb') then
    return format('(%s->%L)::%s', p_json_param, p_column, p_type);
  elsif p_type in ('text','character varying','character') or p_type like 'character varying%' or p_type like 'character%' then
    return format('%s->>%L', p_json_param, p_column);
  else
    return format('nullif(%s->>%L, '''')::%s', p_json_param, p_column, p_type);
  end if;
end;
$$;

create or replace function platform._pwf_owner_write_upsert_jsonb_v1(
  p_schema text,
  p_table text,
  p_key_cols text[],
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, platform
as $$
declare
  v_col record;
  v_cols text[] := array[]::text[];
  v_insert_cols text := '';
  v_insert_vals text := '';
  v_update_sets text := '';
  v_where text := '';
  v_sql text;
  v_result jsonb;
  v_expr text;
  v_has_non_key boolean := false;
  v_key text;
begin
  if not platform._pwf_table_exists_v1(p_schema, p_table) then
    raise exception 'PWF_TARGET_TABLE_MISSING %.%', p_schema, p_table using errcode = 'P0001';
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'PWF_PAYLOAD_OBJECT_REQUIRED' using errcode = 'P0001';
  end if;
  foreach v_key in array p_key_cols loop
    if not platform._pwf_column_exists_v1(p_schema, p_table, v_key) then
      raise exception 'PWF_TARGET_KEY_COLUMN_MISSING %.%.%', p_schema, p_table, v_key using errcode = 'P0001';
    end if;
    if not (p_payload ? v_key) then
      raise exception 'PWF_TARGET_KEY_VALUE_MISSING %', v_key using errcode = 'P0001';
    end if;
  end loop;

  for v_col in
    select a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod) as type_name
    from pg_catalog.pg_attribute a
    join pg_catalog.pg_class c on c.oid = a.attrelid
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    where n.nspname = p_schema
      and c.relname = p_table
      and a.attnum > 0
      and not a.attisdropped
      and (p_payload ? a.attname)
    order by a.attnum
  loop
    v_cols := array_append(v_cols, v_col.attname);
    v_expr := platform._pwf_json_cast_expr_v1('$1', v_col.attname, v_col.type_name);
    v_insert_cols := concat_ws(', ', nullif(v_insert_cols,''), format('%I', v_col.attname));
    v_insert_vals := concat_ws(', ', nullif(v_insert_vals,''), v_expr);
    if not (v_col.attname = any(p_key_cols)) and v_col.attname <> 'created_at' then
      v_has_non_key := true;
      v_update_sets := concat_ws(', ', nullif(v_update_sets,''), format('%I = %s', v_col.attname, v_expr));
    end if;
  end loop;

  if array_length(v_cols, 1) is null then
    raise exception 'PWF_NO_MATCHING_COLUMNS_IN_PAYLOAD %.%', p_schema, p_table using errcode = 'P0001';
  end if;

  foreach v_key in array p_key_cols loop
    select pg_catalog.format_type(a.atttypid, a.atttypmod)
      into v_expr
    from pg_catalog.pg_attribute a
    join pg_catalog.pg_class c on c.oid = a.attrelid
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    where n.nspname = p_schema and c.relname = p_table and a.attname = v_key and a.attnum > 0 and not a.attisdropped;
    v_where := concat_ws(' and ', nullif(v_where,''), format('t.%I = %s', v_key, platform._pwf_json_cast_expr_v1('$1', v_key, v_expr)));
  end loop;

  if v_has_non_key then
    v_sql := format('update %I.%I as t set %s where %s returning to_jsonb(t.*)', p_schema, p_table, v_update_sets, v_where);
    execute v_sql using p_payload into v_result;
    if v_result is not null then
      return v_result;
    end if;
  else
    v_sql := format('select to_jsonb(t.*) from %I.%I as t where %s limit 1', p_schema, p_table, v_where);
    execute v_sql using p_payload into v_result;
    if v_result is not null then
      return v_result;
    end if;
  end if;

  v_sql := format('insert into %I.%I as t (%s) values (%s) returning to_jsonb(t.*)', p_schema, p_table, v_insert_cols, v_insert_vals);
  execute v_sql using p_payload into v_result;
  return v_result;
end;
$$;

create or replace function platform._pwf_owner_write_actor_context_v1()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, core, platform, auth
as $$
declare
  v_actor uuid := auth.uid();
  v_active boolean;
  v_super boolean;
  v_role text;
  v_platform_admin boolean := false;
  v_role_col text;
  v_active_clause text := '';
  v_sql text;
begin
  if v_actor is null then
    raise exception 'PWF_AUTH_REQUIRED' using errcode = 'P0001';
  end if;
  if not platform._pwf_table_exists_v1('core','admin_users') then
    raise exception 'PWF_CORE_ADMIN_USERS_MISSING' using errcode = 'P0001';
  end if;

  execute 'select coalesce(is_active,true), coalesce(is_superuser,false), coalesce(role,'''') from core.admin_users where id = $1'
    into v_active, v_super, v_role using v_actor;

  if v_active is distinct from true then
    raise exception 'PWF_ACTOR_INACTIVE' using errcode = 'P0001';
  end if;

  v_platform_admin := coalesce(v_super,false) or lower(coalesce(v_role,'')) in
    ('superuser','super_user','super-admin','platform_admin','platform-admin','platform_super_admin','root','owner','admin');

  if platform._pwf_table_exists_v1('platform','user_system_roles') then
    if platform._pwf_column_exists_v1('platform','user_system_roles','role_key') then
      v_role_col := 'role_key';
    elsif platform._pwf_column_exists_v1('platform','user_system_roles','role') then
      v_role_col := 'role';
    else
      v_role_col := null;
    end if;
    if platform._pwf_column_exists_v1('platform','user_system_roles','is_active') then
      v_active_clause := ' and coalesce(is_active,true) = true';
    else
      v_active_clause := '';
    end if;
    if v_role_col is not null and platform._pwf_column_exists_v1('platform','user_system_roles','system_key') then
      v_sql := format(
        'select exists(select 1 from platform.user_system_roles where user_id=$1 and lower(system_key::text) in (''platformadmin'',''platform_admin'',''platform-admin'',''platform'',''admin'') and lower(%I::text) in (''superuser'',''super_user'',''platform_admin'',''platform-admin'',''admin'') %s)',
        v_role_col,
        v_active_clause
      );
      execute v_sql into v_platform_admin using v_actor;
      v_platform_admin := v_platform_admin or coalesce(v_super,false);
    end if;
  end if;

  return jsonb_build_object(
    'actor_user_id', v_actor,
    'is_active', coalesce(v_active,false),
    'is_superuser', coalesce(v_super,false),
    'role', coalesce(v_role,''),
    'is_platform_admin', coalesce(v_platform_admin,false)
  );
end;
$$;

create or replace function platform._pwf_owner_write_can_manage_system_v1(p_context jsonb, p_system_key text)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, platform
as $$
declare
  v_actor uuid := (p_context->>'actor_user_id')::uuid;
  v_role_col text;
  v_active_clause text := '';
  v_sql text;
  v_allowed boolean := false;
begin
  if coalesce((p_context->>'is_superuser')::boolean,false) or coalesce((p_context->>'is_platform_admin')::boolean,false) then
    return true;
  end if;
  if p_system_key is null or btrim(p_system_key) = '' then
    return false;
  end if;
  if not platform._pwf_table_exists_v1('platform','user_system_roles') then
    return false;
  end if;
  if platform._pwf_column_exists_v1('platform','user_system_roles','role_key') then
    v_role_col := 'role_key';
  elsif platform._pwf_column_exists_v1('platform','user_system_roles','role') then
    v_role_col := 'role';
  else
    return false;
  end if;
  if platform._pwf_column_exists_v1('platform','user_system_roles','is_active') then
    v_active_clause := ' and coalesce(is_active,true) = true';
  end if;
  v_sql := format('select exists(select 1 from platform.user_system_roles where user_id=$1 and system_key::text=$2 and lower(%I::text) in (''admin'',''manager'',''unit_admin'',''system_admin'') %s)', v_role_col, v_active_clause);
  execute v_sql into v_allowed using v_actor, p_system_key;
  return coalesce(v_allowed,false);
end;
$$;

create or replace function platform._pwf_owner_write_audit_v1(
  p_event_key text,
  p_actor_user_id uuid,
  p_target_schema text,
  p_target_table text,
  p_target_user_id uuid,
  p_target_system_key text,
  p_request_payload jsonb,
  p_result_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, platform
as $$
begin
  insert into platform.owner_write_rpc_audit_events(
    event_key, actor_user_id, target_schema, target_table, target_user_id,
    target_system_key, request_payload, result_payload, correlation_id
  ) values (
    p_event_key,
    p_actor_user_id,
    p_target_schema,
    p_target_table,
    p_target_user_id,
    p_target_system_key,
    coalesce(p_request_payload, '{}'::jsonb),
    coalesce(p_result_payload, '{}'::jsonb),
    coalesce(p_request_payload->>'correlation_id', p_request_payload->>'request_id')
  );
end;
$$;

create or replace function platform._pwf_owner_write_system_exists_v1(p_system_key text)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, platform
as $$
declare
  v_key_col text;
  v_sql text;
  v_exists boolean := false;
begin
  if not platform._pwf_table_exists_v1('platform','platform_systems') then
    return false;
  end if;
  if platform._pwf_column_exists_v1('platform','platform_systems','system_key') then
    v_key_col := 'system_key';
  elsif platform._pwf_column_exists_v1('platform','platform_systems','key') then
    v_key_col := 'key';
  elsif platform._pwf_column_exists_v1('platform','platform_systems','slug') then
    v_key_col := 'slug';
  else
    return false;
  end if;
  v_sql := format('select exists(select 1 from platform.platform_systems where %I::text=$1)', v_key_col);
  execute v_sql into v_exists using p_system_key;
  return coalesce(v_exists,false);
end;
$$;

create or replace function platform._pwf_owner_write_permission_exists_v1(p_system_key text, p_permission_key text)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, platform
as $$
declare
  v_perm_col text;
  v_sql text;
  v_exists boolean := false;
  v_system_filter text := '';
begin
  if not platform._pwf_table_exists_v1('platform','platform_permissions') then
    return false;
  end if;
  if platform._pwf_column_exists_v1('platform','platform_permissions','permission_key') then
    v_perm_col := 'permission_key';
  elsif platform._pwf_column_exists_v1('platform','platform_permissions','key') then
    v_perm_col := 'key';
  elsif platform._pwf_column_exists_v1('platform','platform_permissions','permission') then
    v_perm_col := 'permission';
  else
    return false;
  end if;
  if platform._pwf_column_exists_v1('platform','platform_permissions','system_key') then
    v_system_filter := ' and system_key::text = $2';
    v_sql := format('select exists(select 1 from platform.platform_permissions where %I::text=$1 %s)', v_perm_col, v_system_filter);
    execute v_sql into v_exists using p_permission_key, p_system_key;
  else
    v_sql := format('select exists(select 1 from platform.platform_permissions where %I::text=$1)', v_perm_col);
    execute v_sql into v_exists using p_permission_key;
  end if;
  return coalesce(v_exists,false);
end;
$$;

create or replace function public.rpc_core_admin_user_profile_update_v1(
  p_target_user_id uuid,
  p_patch jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, core, platform, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_is_super boolean;
  v_is_platform_admin boolean;
  v_allowed text[] := array['email','name','username','role','department','governorate','phone','avatar_url','unit_id','is_active','is_superuser','correlation_id','request_id','operation'];
  v_self_allowed text[] := array['name','department','phone','avatar_url','correlation_id','request_id','operation'];
  v_denied text[];
  v_result jsonb;
begin
  if p_target_user_id is null then
    raise exception 'PWF_TARGET_USER_REQUIRED' using errcode = 'P0001';
  end if;
  p_patch := coalesce(p_patch, '{}'::jsonb);
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  v_is_super := coalesce((v_ctx->>'is_superuser')::boolean,false);
  v_is_platform_admin := coalesce((v_ctx->>'is_platform_admin')::boolean,false);

  select array_agg(key) into v_denied
  from jsonb_object_keys(p_patch) as key
  where not (key = any(case when p_target_user_id = v_actor and not (v_is_super or v_is_platform_admin) then v_self_allowed else v_allowed end));
  if v_denied is not null then
    raise exception 'PWF_FORBIDDEN_PROFILE_PATCH_KEYS %', v_denied using errcode = 'P0001';
  end if;

  if p_target_user_id <> v_actor and not (v_is_super or v_is_platform_admin) then
    raise exception 'PWF_ADMIN_PROFILE_UPDATE_FORBIDDEN' using errcode = 'P0001';
  end if;
  if p_target_user_id = v_actor and ((p_patch ? 'is_active') or (p_patch ? 'is_superuser') or (p_patch ? 'role')) then
    raise exception 'PWF_SELF_LOCKOUT_OR_SELF_PRIVILEGE_CHANGE_DENIED' using errcode = 'P0001';
  end if;
  if (p_patch ? 'is_superuser') and (p_patch->>'is_superuser')::boolean = true and not v_is_super then
    raise exception 'PWF_SUPERUSER_GRANT_REQUIRES_SUPERUSER' using errcode = 'P0001';
  end if;

  update core.admin_users as a
  set email = case when p_patch ? 'email' then nullif(p_patch->>'email','') else a.email end,
      name = case when p_patch ? 'name' then nullif(p_patch->>'name','') else a.name end,
      username = case when p_patch ? 'username' then nullif(p_patch->>'username','') else a.username end,
      role = case when p_patch ? 'role' then nullif(p_patch->>'role','') else a.role end,
      department = case when p_patch ? 'department' then nullif(p_patch->>'department','') else a.department end,
      governorate = case when p_patch ? 'governorate' then nullif(p_patch->>'governorate','') else a.governorate end,
      phone = case when p_patch ? 'phone' then nullif(p_patch->>'phone','') else a.phone end,
      avatar_url = case when p_patch ? 'avatar_url' then nullif(p_patch->>'avatar_url','') else a.avatar_url end,
      unit_id = case when p_patch ? 'unit_id' then nullif(p_patch->>'unit_id','')::uuid else a.unit_id end,
      is_active = case when p_patch ? 'is_active' then (p_patch->>'is_active')::boolean else a.is_active end,
      is_superuser = case when p_patch ? 'is_superuser' then (p_patch->>'is_superuser')::boolean else a.is_superuser end,
      updated_at = now()
  where a.id = p_target_user_id
  returning to_jsonb(a.*) into v_result;

  if v_result is null then
    raise exception 'PWF_ADMIN_PROFILE_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform platform._pwf_owner_write_audit_v1('core_admin_user_profile_update', v_actor, 'core', 'admin_users', p_target_user_id, null, p_patch, v_result);
  return jsonb_build_object('success', true, 'message_ar', 'تم تحديث الملف الإداري عبر RPC محكوم.', 'data', v_result);
end;
$$;

create or replace function public.rpc_core_admin_user_link_v1(
  p_target_user_id uuid,
  p_patch jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, core, platform, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_auth_email text;
  v_payload jsonb;
  v_result jsonb;
begin
  if p_target_user_id is null then
    raise exception 'PWF_TARGET_USER_REQUIRED' using errcode = 'P0001';
  end if;
  p_patch := coalesce(p_patch, '{}'::jsonb);
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  if not (coalesce((v_ctx->>'is_superuser')::boolean,false) or coalesce((v_ctx->>'is_platform_admin')::boolean,false)) then
    raise exception 'PWF_ADMIN_LINK_REQUIRES_PLATFORM_ADMIN' using errcode = 'P0001';
  end if;

  select email into v_auth_email from auth.users where id = p_target_user_id;
  if v_auth_email is null then
    raise exception 'PWF_AUTH_IDENTITY_NOT_FOUND_NO_AUTH_USERS_MUTATION' using errcode = 'P0001';
  end if;

  v_payload := jsonb_build_object(
    'id', p_target_user_id,
    'email', coalesce(nullif(p_patch->>'email',''), v_auth_email),
    'name', coalesce(nullif(p_patch->>'name',''), nullif(p_patch->>'username',''), v_auth_email),
    'role', coalesce(nullif(p_patch->>'role',''), 'user'),
    'is_active', coalesce((p_patch->>'is_active')::boolean, true),
    'updated_at', now()
  ) || (p_patch - 'id' - 'password' - 'auth_user' - 'auth.users');

  if not coalesce((v_ctx->>'is_superuser')::boolean,false) and coalesce((v_payload->>'is_superuser')::boolean,false) then
    raise exception 'PWF_SUPERUSER_GRANT_REQUIRES_SUPERUSER' using errcode = 'P0001';
  end if;

  v_result := platform._pwf_owner_write_upsert_jsonb_v1('core','admin_users', array['id'], v_payload);
  perform platform._pwf_owner_write_audit_v1('core_admin_user_link', v_actor, 'core', 'admin_users', p_target_user_id, null, v_payload, v_result);
  return jsonb_build_object('success', true, 'message_ar', 'تم ربط هوية المصادقة ببروفايل إداري دون تعديل auth.users.', 'data', v_result);
end;
$$;

create or replace function public.rpc_core_admin_user_deactivate_v1(
  p_target_user_id uuid,
  p_patch jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, core, platform, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
begin
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  if p_target_user_id = v_actor then
    raise exception 'PWF_SELF_DEACTIVATION_DENIED' using errcode = 'P0001';
  end if;
  if not (coalesce((v_ctx->>'is_superuser')::boolean,false) or coalesce((v_ctx->>'is_platform_admin')::boolean,false)) then
    raise exception 'PWF_DEACTIVATE_REQUIRES_PLATFORM_ADMIN' using errcode = 'P0001';
  end if;
  return public.rpc_core_admin_user_profile_update_v1(
    p_target_user_id,
    coalesce(p_patch,'{}'::jsonb) || jsonb_build_object('is_active', false, 'operation', 'deactivate_profile_only_no_auth_delete')
  );
end;
$$;

create or replace function public.rpc_platform_system_register_v1(
  p_system_key text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, platform, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_key_col text;
  v_payload jsonb;
  v_result jsonb;
begin
  p_system_key := btrim(coalesce(p_system_key,''));
  if p_system_key = '' or p_system_key !~ '^[A-Za-z0-9][A-Za-z0-9_\-]{1,80}$' then
    raise exception 'PWF_INVALID_SYSTEM_KEY' using errcode = 'P0001';
  end if;
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  if not (coalesce((v_ctx->>'is_superuser')::boolean,false) or coalesce((v_ctx->>'is_platform_admin')::boolean,false)) then
    raise exception 'PWF_SYSTEM_REGISTER_REQUIRES_PLATFORM_ADMIN' using errcode = 'P0001';
  end if;
  if platform._pwf_column_exists_v1('platform','platform_systems','system_key') then
    v_key_col := 'system_key';
  elsif platform._pwf_column_exists_v1('platform','platform_systems','key') then
    v_key_col := 'key';
  elsif platform._pwf_column_exists_v1('platform','platform_systems','slug') then
    v_key_col := 'slug';
  else
    raise exception 'PWF_PLATFORM_SYSTEMS_KEY_COLUMN_MISSING' using errcode = 'P0001';
  end if;
  v_payload := coalesce(p_payload,'{}'::jsonb) || jsonb_build_object(v_key_col, p_system_key, 'updated_at', now());
  v_result := platform._pwf_owner_write_upsert_jsonb_v1('platform','platform_systems', array[v_key_col], v_payload);
  perform platform._pwf_owner_write_audit_v1('platform_system_register', v_actor, 'platform', 'platform_systems', null, p_system_key, v_payload, v_result);
  return jsonb_build_object('success', true, 'message_ar', 'تم تسجيل/تحديث النظام عبر RPC محكوم.', 'data', v_result);
end;
$$;

create or replace function public.rpc_platform_user_role_upsert_v1(
  p_target_user_id uuid,
  p_system_key text,
  p_role_key text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, platform, core, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_role_col text;
  v_payload jsonb;
  v_result jsonb;
begin
  p_system_key := btrim(coalesce(p_system_key,''));
  p_role_key := btrim(coalesce(p_role_key,''));
  if p_target_user_id is null or p_system_key = '' or p_role_key = '' then
    raise exception 'PWF_ROLE_UPSERT_REQUIRED_FIELDS_MISSING' using errcode = 'P0001';
  end if;
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  if not platform._pwf_owner_write_can_manage_system_v1(v_ctx, p_system_key) then
    raise exception 'PWF_ROLE_UPSERT_FORBIDDEN_FOR_SYSTEM' using errcode = 'P0001';
  end if;
  if p_target_user_id = v_actor and lower(p_role_key) not in ('viewer','user','employee') then
    raise exception 'PWF_SELF_ROLE_CHANGE_DENIED' using errcode = 'P0001';
  end if;
  if lower(p_role_key) in ('superuser','super_user','platform_admin','platform-admin','root','owner') and not coalesce((v_ctx->>'is_superuser')::boolean,false) then
    raise exception 'PWF_PRIVILEGE_ESCALATION_DENIED' using errcode = 'P0001';
  end if;
  if not platform._pwf_owner_write_system_exists_v1(p_system_key) then
    raise exception 'PWF_SYSTEM_KEY_NOT_REGISTERED' using errcode = 'P0001';
  end if;
  if platform._pwf_column_exists_v1('platform','user_system_roles','role_key') then
    v_role_col := 'role_key';
  elsif platform._pwf_column_exists_v1('platform','user_system_roles','role') then
    v_role_col := 'role';
  else
    raise exception 'PWF_ROLE_COLUMN_MISSING' using errcode = 'P0001';
  end if;
  v_payload := coalesce(p_payload,'{}'::jsonb) || jsonb_build_object('user_id', p_target_user_id, 'system_key', p_system_key, v_role_col, p_role_key, 'is_active', true, 'updated_at', now());
  v_result := platform._pwf_owner_write_upsert_jsonb_v1('platform','user_system_roles', array['user_id','system_key'], v_payload);
  perform platform._pwf_owner_write_audit_v1('platform_user_role_upsert', v_actor, 'platform', 'user_system_roles', p_target_user_id, p_system_key, v_payload, v_result);
  return jsonb_build_object('success', true, 'message_ar', 'تم تحديث دور المستخدم عبر RPC محكوم.', 'data', v_result);
end;
$$;

create or replace function public.rpc_platform_user_role_delete_v1(
  p_target_user_id uuid,
  p_system_key text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, platform, core, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_payload jsonb;
  v_result jsonb;
begin
  p_system_key := btrim(coalesce(p_system_key,''));
  if p_target_user_id is null or p_system_key = '' then
    raise exception 'PWF_ROLE_DELETE_REQUIRED_FIELDS_MISSING' using errcode = 'P0001';
  end if;
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  if p_target_user_id = v_actor then
    raise exception 'PWF_SELF_LOCKOUT_ROLE_DELETE_DENIED' using errcode = 'P0001';
  end if;
  if not platform._pwf_owner_write_can_manage_system_v1(v_ctx, p_system_key) then
    raise exception 'PWF_ROLE_DELETE_FORBIDDEN_FOR_SYSTEM' using errcode = 'P0001';
  end if;
  if not platform._pwf_column_exists_v1('platform','user_system_roles','is_active') then
    raise exception 'PWF_SOFT_ROLE_DELETE_REQUIRES_IS_ACTIVE_COLUMN' using errcode = 'P0001';
  end if;
  v_payload := coalesce(p_payload,'{}'::jsonb) || jsonb_build_object('user_id', p_target_user_id, 'system_key', p_system_key, 'is_active', false, 'updated_at', now());
  v_result := platform._pwf_owner_write_upsert_jsonb_v1('platform','user_system_roles', array['user_id','system_key'], v_payload);
  perform platform._pwf_owner_write_audit_v1('platform_user_role_soft_delete', v_actor, 'platform', 'user_system_roles', p_target_user_id, p_system_key, v_payload, v_result);
  return jsonb_build_object('success', true, 'message_ar', 'تم تعطيل الدور دون حذف فيزيائي.', 'data', v_result);
end;
$$;

create or replace function public.rpc_platform_user_permission_grant_v1(
  p_target_user_id uuid,
  p_system_key text,
  p_permission_key text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, platform, core, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_perm_col text;
  v_payload jsonb;
  v_result jsonb;
begin
  p_system_key := btrim(coalesce(p_system_key,''));
  p_permission_key := btrim(coalesce(p_permission_key,''));
  if p_target_user_id is null or p_system_key = '' or p_permission_key = '' then
    raise exception 'PWF_PERMISSION_GRANT_REQUIRED_FIELDS_MISSING' using errcode = 'P0001';
  end if;
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  if not platform._pwf_owner_write_can_manage_system_v1(v_ctx, p_system_key) then
    raise exception 'PWF_PERMISSION_GRANT_FORBIDDEN_FOR_SYSTEM' using errcode = 'P0001';
  end if;
  if not platform._pwf_owner_write_permission_exists_v1(p_system_key, p_permission_key) then
    raise exception 'PWF_PERMISSION_NOT_IN_CATALOG' using errcode = 'P0001';
  end if;
  if platform._pwf_column_exists_v1('platform','user_system_permissions','permission_key') then
    v_perm_col := 'permission_key';
  elsif platform._pwf_column_exists_v1('platform','user_system_permissions','permission') then
    v_perm_col := 'permission';
  else
    raise exception 'PWF_PERMISSION_COLUMN_MISSING' using errcode = 'P0001';
  end if;
  v_payload := coalesce(p_payload,'{}'::jsonb) || jsonb_build_object('user_id', p_target_user_id, 'system_key', p_system_key, v_perm_col, p_permission_key, 'allow', true, 'is_active', true, 'updated_at', now());
  v_result := platform._pwf_owner_write_upsert_jsonb_v1('platform','user_system_permissions', array['user_id','system_key',v_perm_col], v_payload);
  perform platform._pwf_owner_write_audit_v1('platform_user_permission_grant', v_actor, 'platform', 'user_system_permissions', p_target_user_id, p_system_key, v_payload, v_result);
  return jsonb_build_object('success', true, 'message_ar', 'تم منح الصلاحية عبر RPC محكوم.', 'data', v_result);
end;
$$;

create or replace function public.rpc_platform_user_permission_revoke_v1(
  p_target_user_id uuid,
  p_system_key text,
  p_permission_key text,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, platform, core, auth
as $$
declare
  v_ctx jsonb;
  v_actor uuid;
  v_perm_col text;
  v_payload jsonb;
  v_result jsonb;
begin
  p_system_key := btrim(coalesce(p_system_key,''));
  p_permission_key := btrim(coalesce(p_permission_key,''));
  if p_target_user_id is null or p_system_key = '' or p_permission_key = '' then
    raise exception 'PWF_PERMISSION_REVOKE_REQUIRED_FIELDS_MISSING' using errcode = 'P0001';
  end if;
  v_ctx := platform._pwf_owner_write_actor_context_v1();
  v_actor := (v_ctx->>'actor_user_id')::uuid;
  if p_target_user_id = v_actor and lower(p_permission_key) in ('admin','manage_users','manage_roles','manage_permissions','delete') then
    raise exception 'PWF_SELF_LOCKOUT_PERMISSION_REVOKE_DENIED' using errcode = 'P0001';
  end if;
  if not platform._pwf_owner_write_can_manage_system_v1(v_ctx, p_system_key) then
    raise exception 'PWF_PERMISSION_REVOKE_FORBIDDEN_FOR_SYSTEM' using errcode = 'P0001';
  end if;
  if platform._pwf_column_exists_v1('platform','user_system_permissions','permission_key') then
    v_perm_col := 'permission_key';
  elsif platform._pwf_column_exists_v1('platform','user_system_permissions','permission') then
    v_perm_col := 'permission';
  else
    raise exception 'PWF_PERMISSION_COLUMN_MISSING' using errcode = 'P0001';
  end if;
  v_payload := coalesce(p_payload,'{}'::jsonb) || jsonb_build_object('user_id', p_target_user_id, 'system_key', p_system_key, v_perm_col, p_permission_key, 'allow', false, 'is_active', false, 'updated_at', now());
  v_result := platform._pwf_owner_write_upsert_jsonb_v1('platform','user_system_permissions', array['user_id','system_key',v_perm_col], v_payload);
  perform platform._pwf_owner_write_audit_v1('platform_user_permission_revoke', v_actor, 'platform', 'user_system_permissions', p_target_user_id, p_system_key, v_payload, v_result);
  return jsonb_build_object('success', true, 'message_ar', 'تم سحب الصلاحية الصريحة عبر RPC محكوم دون المساس بالصلاحيات الموروثة.', 'data', v_result);
end;
$$;

revoke all on function public.rpc_core_admin_user_profile_update_v1(uuid,jsonb) from public;
revoke all on function public.rpc_core_admin_user_link_v1(uuid,jsonb) from public;
revoke all on function public.rpc_core_admin_user_deactivate_v1(uuid,jsonb) from public;
revoke all on function public.rpc_platform_system_register_v1(text,jsonb) from public;
revoke all on function public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb) from public;
revoke all on function public.rpc_platform_user_role_delete_v1(uuid,text,jsonb) from public;
revoke all on function public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb) from public;
revoke all on function public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb) from public;
revoke all on function public.rpc_core_admin_user_profile_update_v1(uuid,jsonb) from anon;
revoke all on function public.rpc_core_admin_user_link_v1(uuid,jsonb) from anon;
revoke all on function public.rpc_core_admin_user_deactivate_v1(uuid,jsonb) from anon;
revoke all on function public.rpc_platform_system_register_v1(text,jsonb) from anon;
revoke all on function public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb) from anon;
revoke all on function public.rpc_platform_user_role_delete_v1(uuid,text,jsonb) from anon;
revoke all on function public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb) from anon;
revoke all on function public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb) from anon;

do $$
begin
  if exists (select 1 from pg_catalog.pg_roles where rolname = 'authenticated') then
    grant execute on function public.rpc_core_admin_user_profile_update_v1(uuid,jsonb) to authenticated;
    grant execute on function public.rpc_core_admin_user_link_v1(uuid,jsonb) to authenticated;
    grant execute on function public.rpc_core_admin_user_deactivate_v1(uuid,jsonb) to authenticated;
    grant execute on function public.rpc_platform_system_register_v1(text,jsonb) to authenticated;
    grant execute on function public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb) to authenticated;
    grant execute on function public.rpc_platform_user_role_delete_v1(uuid,text,jsonb) to authenticated;
    grant execute on function public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb) to authenticated;
    grant execute on function public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb) to authenticated;
  end if;
end $$;

commit;
