-- Platform Development 10C
-- Post-anon-revoke catalog UAT: read-only.

with checks(section, check_key, passed, note) as (
  values
    ('function_presence', 'public.rpc_core_admin_user_profile_update_v1(uuid,jsonb)', to_regprocedure('public.rpc_core_admin_user_profile_update_v1(uuid,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_core_admin_user_profile_update_v1(uuid,jsonb)', has_function_privilege('authenticated', 'public.rpc_core_admin_user_profile_update_v1(uuid,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_core_admin_user_profile_update_v1(uuid,jsonb)', not has_function_privilege('anon', 'public.rpc_core_admin_user_profile_update_v1(uuid,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('function_presence', 'public.rpc_core_admin_user_link_v1(uuid,jsonb)', to_regprocedure('public.rpc_core_admin_user_link_v1(uuid,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_core_admin_user_link_v1(uuid,jsonb)', has_function_privilege('authenticated', 'public.rpc_core_admin_user_link_v1(uuid,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_core_admin_user_link_v1(uuid,jsonb)', not has_function_privilege('anon', 'public.rpc_core_admin_user_link_v1(uuid,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('function_presence', 'public.rpc_core_admin_user_deactivate_v1(uuid,jsonb)', to_regprocedure('public.rpc_core_admin_user_deactivate_v1(uuid,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_core_admin_user_deactivate_v1(uuid,jsonb)', has_function_privilege('authenticated', 'public.rpc_core_admin_user_deactivate_v1(uuid,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_core_admin_user_deactivate_v1(uuid,jsonb)', not has_function_privilege('anon', 'public.rpc_core_admin_user_deactivate_v1(uuid,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('function_presence', 'public.rpc_platform_system_register_v1(text,jsonb)', to_regprocedure('public.rpc_platform_system_register_v1(text,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_platform_system_register_v1(text,jsonb)', has_function_privilege('authenticated', 'public.rpc_platform_system_register_v1(text,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_platform_system_register_v1(text,jsonb)', not has_function_privilege('anon', 'public.rpc_platform_system_register_v1(text,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('function_presence', 'public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb)', to_regprocedure('public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb)', has_function_privilege('authenticated', 'public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb)', not has_function_privilege('anon', 'public.rpc_platform_user_role_upsert_v1(uuid,text,text,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('function_presence', 'public.rpc_platform_user_role_delete_v1(uuid,text,jsonb)', to_regprocedure('public.rpc_platform_user_role_delete_v1(uuid,text,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_platform_user_role_delete_v1(uuid,text,jsonb)', has_function_privilege('authenticated', 'public.rpc_platform_user_role_delete_v1(uuid,text,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_platform_user_role_delete_v1(uuid,text,jsonb)', not has_function_privilege('anon', 'public.rpc_platform_user_role_delete_v1(uuid,text,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('function_presence', 'public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb)', to_regprocedure('public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb)', has_function_privilege('authenticated', 'public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb)', not has_function_privilege('anon', 'public.rpc_platform_user_permission_grant_v1(uuid,text,text,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('function_presence', 'public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb)', to_regprocedure('public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb)') is not null, 'Owner-write RPC should remain installed after anon revoke hotfix.'),
    ('authenticated_execute', 'public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb)', has_function_privilege('authenticated', 'public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb)', 'execute'), 'authenticated must retain execute privilege; SQL guards enforce actor permissions.'),
    ('anon_blocked', 'public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb)', not has_function_privilege('anon', 'public.rpc_platform_user_permission_revoke_v1(uuid,text,text,jsonb)', 'execute'), 'anon must not execute owner-write RPCs after 10C hotfix.'),
    ('runtime_flag', 'owner_write_rpc_anon_execute_revoked_v1', coalesce((select is_enabled from platform.owner_write_rpc_runtime_flags where flag_key = 'owner_write_rpc_anon_execute_revoked_v1'), false), '10C privilege hotfix flag should be true.'),
    ('sovereign_boundary', 'no_auth_users_migration', true, 'Hotfix revokes function privileges only; auth.users remains Supabase Auth identity source.'),
    ('sovereign_boundary', 'no_waqf_assets_mutation', true, 'Hotfix contains no waqf_assets/waqf/awqaf_system DDL or DML.')
)
select * from checks order by section, check_key;
