-- Platform Development 10H
-- Production Gate Re-Decision Template After Actual Negative UAT Evidence (read-only)
-- Fill the evidence values only after attaching generated runner JSON/MD + admin/write console proof.

select * from (values
  ('gate_input','runner_json_attached',false,'Attach actual_negative_uat_results_*.json generated by the 10H Dart runner.'),
  ('gate_input','runner_markdown_attached',false,'Attach actual_negative_uat_results_*.md generated by the 10H Dart runner.'),
  ('gate_input','all_required_actor_cases_denied',false,'Must be true in generated JSON.'),
  ('gate_input','unsafe_success_count_zero',false,'Must be zero in generated JSON.'),
  ('gate_input','admin_write_surface_console_clean',false,'Attach browser console evidence from admin/write surfaces.'),
  ('gate_input','sql_rls_no_unsafe_mutation_proof',false,'Attach DB proof that denied attempts caused no unsafe mutation.'),
  ('production_gate','flutter_write_reroute_production_enabled',false,'Production reroute remains disabled until all evidence passes.'),
  ('production_gate','production_approved',false,'Not approved by this template.'),
  ('sovereign_boundary','no_auth_users_migration',true,'auth.users remains identity source.'),
  ('sovereign_boundary','no_flutter_elevated_secret',true,'No service_role/elevated secret is used by the runner.'),
  ('sovereign_boundary','no_waqf_assets_mutation',true,'No waqf_assets/waqf/awqaf_system mutation is authorized.')
) as t(section, check_key, passed, note);
